import { z } from "zod";

import { resolveGhostcrabConfig } from "../../config/env.js";
import {
  createTextToolResult,
  createToolErrorResult,
  registerTool,
  type ToolHandler
} from "../registry.js";
import { WorkspaceIdSchema } from "../../types/workspace.js";
import { runStandaloneWorkspaceExportToon } from "../../db/standalone-mindbrain.js";

const WorkspaceExportToonInput = z.object({
  workspace_id: WorkspaceIdSchema
});

export const workspaceExportToonTool: ToolHandler = {
  definition: {
    name: "ghostcrab_workspace_export_model_toon",
    description:
      "Export workspace semantic model as TOON generated by the Zig standalone engine.",
    inputSchema: {
      type: "object",
      required: ["workspace_id"],
      properties: {
        workspace_id: {
          type: "string",
          description: "Target workspace id."
        }
      }
    }
  },
  async handler(args, context) {
    const input = WorkspaceExportToonInput.parse(args);

    if (context.database.kind !== "sqlite") {
      return createToolErrorResult(
        "ghostcrab_workspace_export_model_toon",
        "The TOON export tool currently requires the SQLite backend.",
        "backend_not_supported"
      );
    }

    const config = resolveGhostcrabConfig();
    const toon = await runStandaloneWorkspaceExportToon({
      mindbrainUrl: config.mindbrainUrl,
      workspaceId: input.workspace_id
    });

    return createTextToolResult(toon);
  }
};

registerTool(workspaceExportToonTool);
