import type { DatabaseClient } from "./client.js";
import type {
  GeneratedTriggerSQL,
  TriggerGeneratorOptions
} from "./trigger-generator.js";
import { generateSyncTrigger } from "./trigger-generator.js";

export type { GeneratedTriggerSQL, TriggerGeneratorOptions } from "./trigger-generator.js";

export async function triggerPreviewFromNative(
  db: DatabaseClient,
  options: TriggerGeneratorOptions,
  pgMindbrain: boolean
): Promise<GeneratedTriggerSQL> {
  if (pgMindbrain) {
    try {
      const syncSpec = {
        source_table: options.sourceTable,
        fields: options.fields
      };
      const [row] = await db.query<{ sql: string }>(
        `SELECT mb_ontology.generate_triggers($1::text, $2::jsonb) AS sql`,
        [options.workspaceId, JSON.stringify(syncSpec)]
      );
      const sqlText = row?.sql?.trim();
      if (sqlText) {
        const safeBase = options.sourceTable
          .replace(/[^a-zA-Z0-9_.]/g, "_")
          .replace(/\./g, "_");
        return {
          triggerName: `trg_mindbrain_sync_${safeBase}`,
          functionName: `mindbrain_sync_${safeBase}`,
          sql: row.sql,
          summary: "Generated by mb_ontology.generate_triggers()."
        };
      }
    } catch {
      // Fall back to local deterministic generation when the native surface
      // is unavailable or does not support trigger preview yet.
    }
  }

  return generateSyncTrigger(options);
}
