import { describe, expect, it, vi } from "vitest";

import type { DatabaseClient } from "../../src/db/client.js";
import { triggerPreviewFromNative } from "../../src/db/native-trigger-preview.js";

function createMockDatabase(queryImpl: DatabaseClient["query"]): DatabaseClient {
  return {
    kind: "sqlite",
    query: queryImpl,
    ping: async () => true,
    close: async () => undefined,
    transaction: async () => {
      throw new Error("transaction not used");
    }
  };
}

describe("triggerPreviewFromNative", () => {
  it("uses mb_ontology.generate_triggers when available", async () => {
    const query = vi.fn<DatabaseClient["query"]>(async () => [
      {
        sql: "CREATE OR REPLACE FUNCTION mindbrain_sync_public_articles() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END; $$;"
      }
    ]);

    const preview = await triggerPreviewFromNative(
      createMockDatabase(query),
      {
        sourceTable: "public.articles",
        workspaceId: "default",
        fields: [
          {
            column_name: "title",
            facet_key: "title",
            facet_type: "term",
            index_in_bm25: true
          }
        ]
      },
      true
    );

    expect(query).toHaveBeenCalledOnce();
    expect(query.mock.calls[0]?.[0]).toContain("mb_ontology.generate_triggers");
    expect(preview.summary).toBe("Generated by mb_ontology.generate_triggers().");
    expect(preview.sql).toContain("mindbrain_sync_public_articles");
  });

  it("falls back to local trigger generation when native preview fails", async () => {
    const query = vi.fn<DatabaseClient["query"]>(async () => {
      throw new Error("native unavailable");
    });

    const preview = await triggerPreviewFromNative(
      createMockDatabase(query),
      {
        sourceTable: "public.articles",
        workspaceId: "default",
        fields: [
          {
            column_name: "title",
            facet_key: "title",
            facet_type: "term",
            index_in_bm25: true
          }
        ]
      },
      true
    );

    expect(query).toHaveBeenCalledOnce();
    expect(preview.summary).not.toBe("Generated by mb_ontology.generate_triggers().");
    expect(preview.triggerName).toContain("trg_mindbrain_sync_public_articles");
    expect(preview.functionName).toContain("mindbrain_sync_public_articles");
  });
});
